name: 🐞 버그 리포트
description: 발견된 버그를 보고하는 템플릿입니다.
title: "[Bug] "
body:
  - type: textarea
    id: what-bug
    attributes:
      label: "## 어떤 버그인가요?"
      description: "발생한 버그에 대해 간결히 설명해주세요"
      placeholder: "ex) 로그인 후 새로고침 시 로그인이 해제됩니다."
    validations:
      required: true

  - type: textarea
    id: when-bug-happens
    attributes:
      label: "## 어떤 상황에서 발생한 버그인가요?"
      description: "가능하면 Given-When-Then 형식으로 구체적으로 작성해주세요"
      placeholder: |
        Given: 로그인한 상태에서
        When: 페이지를 새로고침하면
        Then: 로그인이 해제됩니다.
    validations:
      required: true

  - type: textarea
    id: expected-result
    attributes:
      label: "## 예상 결과"
      description: "정상 동작 시 어떤 결과가 나와야 하는지 설명해주세요"
      placeholder: "ex) 로그인 상태가 유지되어야 합니다."
    validations:
      required: true

  - type: textarea
    id: bug-references
    attributes:
      label: "## 참고할만한 자료 (선택)"
      description: "관련 문서나 링크가 있다면 적어주세요"
      placeholder: "ex) https://github.com/axios/axios/issues/1234"
    validations:
      required: false
