name: ✨ 기능 추가
description: 새로운 기능을 제안하거나 작업할 때 사용하는 템플릿입니다.
title: "[Feat] "
body:
  - type: textarea
    id: feature-overview
    attributes:
      label: "## 어떤 기능인가요?"
      description: "추가하려는 기능에 대해 간결하게 설명해주세요"
      placeholder: "ex) 사용자의 프로필 정보를 수정할 수 있는 기능을 추가합니다."
    validations:
      required: true

  - type: checkboxes
    id: feature-tasks
    attributes:
      label: "## 작업 상세 내용"
      description: "이 기능을 구현하기 위해 필요한 작업을 체크박스로 작성해주세요"
      options:
        - label: "TODO 1"
        - label: "TODO 2"
        - label: "TODO 3"

  - type: textarea
    id: references
    attributes:
      label: "## 참고할만한 자료 (선택)"
      description: "참고한 문서나 링크가 있다면 적어주세요"
      placeholder: "ex) https://react-query.tanstack.com/"
    validations:
      required: false
