name: 📄 회의록 작성
description: 정기/비정기 회의 내용을 기록합니다.
title: "[회의록] "
labels: ["회의록"]
body:
  - type: input
    id: date
    attributes:
      label: 📅 날짜
      placeholder: 예시) 2025-04-10
    validations:
      required: true

  - type: textarea
    id: participants
    attributes:
      label: 👥 참여자
      description: 회의에 참여한 사람들의 이름을 작성해주세요.
      placeholder: 예시) 박한경, 정찬우
    validations:
      required: true

  - type: textarea
    id: todo
    attributes:
      label: 👍 오늘 작업
      description: 오늘 하루 작업 내역을 자유롭게 작성해주세요.
      placeholder: |
        - 백엔드 서버 구축
        - 백엔드 인프라 설정
    validations:
      required: true

  - type: textarea
    id: result
    attributes:
      label: 🧭 회의 결과
      description: 회의에서 결정된 내용, 논의된 항목을 자유롭게 작성해주세요.
      placeholder: |
        - 프로젝트 주제 확정: Backoffice (기업용 인사 관리 시스템)
        - 핵심 기능 선정: 근태관리, 직원관리, 휴가관리, 급여관리
        - 기술 스택 확정: Spring Boot, React, PostgreSQL 등
    validations:
      required: true

  - type: textarea
    id: todos
    attributes:
      label: 📌 다음 회의 안건
      description: 다음 회의에서 다룰 항목이나 준비할 내용을 작성해주세요.
      placeholder: |
        - ERD 및 DB 설계
        - 화면 구성 목록 작성
        - 우선순위 기능 선정
    validations:
      required: false
